module.exports = {
    src: './src',
    schema: './src/relay/schema.graphql',
    language: 'typescript',
    artifactDirectory: './src/relay/__generated__',
    customScalars: {
      uuid: 'string',
      int8: 'string',
      bigint: 'string',
      numeric: 'number',
      varbit: 'string',
      bit: 'string',
      char: 'string',
      varchar: 'string',
      bool: 'boolean',
      int: 'number',
      int4: 'number',
      float8: 'number',
      timestamptz: 'string',
      timetz: 'string',
      jsonb: 'Record<string, unknown>',
      _text: 'string[]',
      citext: 'string',
      date: 'string',
    },
    exclude: [
      '**/node_modules/**',
      '**/__mocks__/**',
      '**/__generated__/**',
      '**/*.graphql',
    ],
  };
  